---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2019/7/18 14:30
---
local skynet = require "skynet"
local cons={} -- { fd , ip  }
local room={}
--进入房间
-- cons { fd , ip , roomIndex }
function room.join(fd,addr)
    cons[fd]={fd=fd,addr=addr}
    print(fd.."||"..addr.."进入房间")
end
skynet.start(function ()
    skynet.dispatch("lua", function(session, source, cmd, subcmd, ...)
        if cmd == "room" then
            local f = room[subcmd]
            f(...)
            -- socket api don't need return
        end
    end)
end)